server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/example_db
    username: example
    password: example
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE