# Hayagriva Format
# https://github.com/typst/hayagriva/blob/main/docs/file-format.md

anatomyOfAUserStory:
  type: Web
  title: The Anatomy of a User Story
  author: Jim Schiel
  publisher: ScrumAlliance
  url: https://resources.scrumalliance.org/Article/anatomy-user-story

baeldungBean:
  type: Web
  title: What Is a Spring Bean
  author: Nguyen Nam Thai
  publisher: baeldung
  url: https://www.baeldung.com/spring-bean

geeksForGeeksSpringDependencyInjection:
  type: Web
  title: Spring Boot - Dependency Injection and Spring Beans
  author: geekforgs9hp
  publisher: GeeksforGeeks
  url: https://www.geeksforgeeks.org/advance-java/spring-boot-dependency-injection-and-spring-beans/

springContainerOverview:
  type: Web
  title: Container Overview
  publisher: Broadcom
  url: https://docs.spring.io/spring-framework/reference/core/beans/basics.html

springDependencyInjection:
  type: Web
  title: Depency Injection
  publisher: Broadcom
  url: https://docs.spring.io/spring-framework/reference/core/beans/dependencies/factory-collaborators.html

springSetterDependencyInjection:
  type: Web
  title: Setter-based Dependency Injection
  url: https://docs.spring.io/spring-framework/reference/core/beans/dependencies/factory-collaborators.html#beans-setter-injection

springContructorDependencyInjection:
  type: Web
  title: Constructor-based Dependency Injection
  url: https://docs.spring.io/spring-framework/reference/core/beans/dependencies/factory-collaborators.html#beans-constructor-injection

springMethodInjection:
  type: Web
  title: Method Injection
  publisher: Broadcom
  url: https://docs.spring.io/spring-framework/reference/core/beans/dependencies/factory-method-injection.html

springBeanScopes:
  type: Web
  title: Bean Scopes
  publisher: Broadcom
  url: https://docs.spring.io/spring-framework/reference/core/beans/factory-scopes.html#beans-factory-scopes-singleton

springWebSocketScope:
  type: Web
  title: WebSocket Scope
  publisher: Broadcom
  url: https://docs.spring.io/spring-framework/reference/web/websocket/stomp/scope.html

stateOfCss2025:
  type: Web
  title: State of CSS 2025
  url: https://2025.stateofcss.com/en-US/other-tools/

springbootOverview:
  type: Web
  title: Spring Boot
  url: https://spring.io/projects/spring-boot

springFrameworkOverview:
  type: Web
  title: Spring Framework Overview
  url: https://docs.spring.io/spring-framework/reference/overview.html

springFrameworkHistory:
  type: Web
  title: History of Spring and the Spring Framework
  url: https://docs.spring.io/spring-framework/reference/overview.html#overview-history

springAndSpringBootComparison:
  type: Web
  title: A Comparison Between Spring and Spring Boot
  publisher: Baeldung
  author: baeldung
  date: 2024-05-11
  url: https://www.baeldung.com/spring-vs-spring-boot

whatIsREST:
  type: Web
  title: What is REST?
  publisher: Codecademy Team
  url: https://www.codecademy.com/article/what-is-rest

httpSpecsGET:
  type: Web
  title: Method Definitions - GET
  url: https://httpwg.org/specs/rfc9110.html#GET

httpSpecsPOST:
  type: Web
  title: Method Definitions - POST
  url: https://httpwg.org/specs/rfc9110.html#POST

httpSpecsPUT:
  type: Web
  title: Method Definitions - PUT
  url: https://httpwg.org/specs/rfc9110.html#PUT

httpSpecsDELETE:
  type: Web
  title: Method Definitions - DELETE
  url: https://httpwg.org/specs/rfc9110.html#DELETE

idempotentMethods:
  type: Web
  title: Idempotent Methods
  url: https://httpwg.org/specs/rfc9110.html#idempotent.methods

httpStatusCodes:
  type: Web
  title: Status Codes
  url: https://httpwg.org/specs/rfc9110.html#status.codes

modelViewControllerMdn:
  type: Web
  title: MVC
  url: https://developer.mozilla.org/en-US/docs/Glossary/MVC

ormWikipedia:
  type: Web
  title: Object–relational mapping
  publisher: Wikipedia
  url: https://en.wikipedia.org/wiki/Object%E2%80%93relational_mapping

ormItSchulung:
  type: Web
  title: Was ist Object-Relational Mapping (ORM)
  publisher: IT-Schulungen.com
  url: https://www.it-schulungen.com/wir-ueber-uns/wissensblog/was-ist-object-relational-mapping-orm.html

codecademyCRUD:
  type: Web
  title: What is CRUD? Explained
  url: https://www.codecademy.com/article/what-is-crud-explained

springMappingRequests:
  type: Web
  title: Mapping Requests
  url: https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller/ann-requestmapping.html

springControllersUriPatterns:
  type: Web
  title: URI Patterns
  url: https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller/ann-requestmapping.html#mvc-ann-requestmapping-uri-templates

springRestErrorHandling:
  type: Web
  title: Error Handling for REST with Spring in Kotlin
  url: https://www.baeldung.com/kotlin/spring-rest-error-handling

springControllerAdvice:
  type: Web
  title: Controller Advice
  url: https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller/ann-advice.html

transactions101:
  type: Web
  title: "Transactions 101: when and how to use them in the Spring Framework"
  url: https://www.twoday.lt/blog/transactions-101-when-and-how-to-use-them-in-the-spring-framework

whenToUseTransactionalStackOverflow:
  type: Web
  title: When should we use @Transactional annotation?
  url: https://stackoverflow.com/questions/78132448/when-should-we-use-transactional-annotation

springJpaEntites:
  type: Web
  title: Defining JPA Entities
  url: https://www.baeldung.com/jpa-entities

springHibernateOneToMany:
  type: Web
  title: Hibernate One to Many
  url: https://www.baeldung.com/hibernate-one-to-many

mediumSpringOneToMany:
  type: Web
  title: Spring Boot One To Many Relationship
  url: https://medium.com/@hk09/spring-boot-one-to-many-relationship-e617183b7861

springOneToOne:
  type: Web
  title: One-to-One Relationship in JPA
  url: https://www.baeldung.com/jpa-one-to-one

springManyToMany:
  type: Web
  title: Many-To-Many Relationship in JPA
  url: https://www.baeldung.com/jpa-many-to-Many

inversionOfControlMartinFowler:
  type: Web
  title: Inversion of Control
  author: Martin Fowler
  url: https://martinfowler.com/bliki/InversionOfControl.html

inversionOfControlDesigningReusableClasses:
  type: Web
  title: Designing Reusable Classes
  author: ["Ralph E. Johnson", "Brian Foote"]
  url: http://www.laputan.org/drc/drc.html

inversionOfControlContainersDependencyInjection:
  type: Web
  title: Inversion of Control Containers and the Dependency Injection pattern
  author: Martin Fowler
  url: https://martinfowler.com/articles/injection.html

designPatternsElementsOfReusableSoftare:
  type: Book
  title: "Design Patterns: Elements of Reusable Object-Oriented Software"
  author: ["Erich Gamma", "Richard Helm", "Ralph Johnson", "John Vlissides"]
  date: 1994

designPatternsSingleton:
  type: chapter
  title: "Design Patterns: Elements of Reusable Object-Oriented Software"
  author: ["Erich Gamma", "Richard Helm", "Ralph Johnson", "John Vlissides"]
  chapter: "Singleton"
  date: 1994
  page-range: 127-134

designPatternsPrototype:
  type: chapter
  title: "Design Patterns: Elements of Reusable Object-Oriented Software"
  author: ["Erich Gamma", "Richard Helm", "Ralph Johnson", "John Vlissides"]
  chapter: "Prototype"
  date: 1994
  page-range: 117-126

restApiDesignRulebook:
  type: Book
  title: REST API Design Rulebook
  author: Mark Massé
  date: 2012

springDataJpaIntroductionBaeldung:
  type: Web
  title: Introduction to Spring Data JPA
  author: Eugen Paraschiv
  url: https://www.baeldung.com/the-persistence-layer-with-spring-data-jpa

springDataOverviewDocs:
  type: Web
  title: Spring Data
  url: https://spring.io/projects/spring-data#overview

springDataJpaOverview:
  type: Web
  title: Spring Data JPA
  url: https://spring.io/projects/spring-data-jpa

springDataJpaGettingStarted:
  type: Web
  title: Getting Started
  url: https://docs.spring.io/spring-data/jpa/reference/jpa/getting-started.html

springDataJpaCoreConcepts:
  type: Web
  title: Core Concepts
  url: https://docs.spring.io/spring-data/jpa/reference/repositories/core-concepts.html

springDataJpaDefiningQueryMethods:
  type: Web
  title: Defining Query Methods
  url: https://docs.spring.io/spring-data/jpa/reference/repositories/query-methods-details.html

oreillyRestfulWebAPIs:
  type: Book
  title: RESTful Web APIs
  publisher: "O’Reilly Media, Inc."
  author: ["Leonard Richardson", "Mike Amundsen"]
  date: 2013

jpaWithSpringBoot:
  type: Web
  title: "JPA with Spring Boot: A Comprehensive Guide with Examples"
  url: https://medium.com/@bshiramagond/jpa-with-spring-boot-a-comprehensive-guide-with-examples-e07da6f3d385

jpaQueryCreation:
  type: Web
  title: Query Creation
  url: https://docs.spring.io/spring-data/jpa/reference/jpa/query-methods.html#jpa.query-methods.query-creation

jpaSorting:
  type: Web
  title: Using Sort
  url: https://docs.spring.io/spring-data/jpa/reference/jpa/query-methods.html#jpa.query-methods.sorting

springUnitTesting:
  type: Web
  title: Unit Testing
  url: https://docs.spring.io/spring-framework/reference/testing/unit.html

backendUnitTestsKotlinSpringboot:
  type: Web
  title: Backend Unit Test with Kotlin and Spring Boot (JUnit&Mockk)
  url: https://medium.com/yildiztech/backend-unit-test-with-kotlin-and-spring-boot-junit-mockk-5563e2d133ca

mockkExample:
  type: Web
  title: Mockk Getting Started
  url: https://mockk.io/?source=post_page-----5563e2d133ca---------------------------------------
