# Hayagriva Format
# https://github.com/typst/hayagriva/blob/main/docs/file-format.md

anatomyOfAUserStory:
  type: Web
  title: The Anatomy of a User Story
  author: Jim Schiel
  publisher: ScrumAlliance
  url: https://resources.scrumalliance.org/Article/anatomy-user-story

baeldungBean:
  type: Web
  title: What Is a Spring Bean
  author: Nguyen Nam Thai
  publisher: baeldung
  url: https://www.baeldung.com/spring-bean

geeksForGeeksSpringDependencyInjection:
  type: Web
  title: Spring Boot - Dependency Injection and Spring Beans
  author: geekforgs9hp
  publisher: GeeksforGeeks
  url: https://www.geeksforgeeks.org/advance-java/spring-boot-dependency-injection-and-spring-beans/

springContainerOverview:
  type: Web
  title: Container Overview
  publisher: Broadcom
  url: https://docs.spring.io/spring-framework/reference/core/beans/basics.html

springDependencyInjection:
  type: Web
  title: Depency Injection
  publisher: Broadcom
  url: https://docs.spring.io/spring-framework/reference/core/beans/dependencies/factory-collaborators.html

springMethodInjection:
  type: Web
  title: Method Injection
  publisher: Broadcom
  url: https://docs.spring.io/spring-framework/reference/core/beans/dependencies/factory-method-injection.html

springBeanScopes:
  type: Web
  title: Bean Scopes
  publisher: Broadcom
  url: https://docs.spring.io/spring-framework/reference/core/beans/factory-scopes.html#beans-factory-scopes-singleton

springWebSocketScope:
  type: Web
  title: WebSocket Scope
  publisher: Broadcom
  url: https://docs.spring.io/spring-framework/reference/web/websocket/stomp/scope.html

stateOfCss2025:
  type: Web
  title: State of CSS 2025
  url: https://2025.stateofcss.com/en-US/other-tools/

springbootOverview:
  type: Web
  title: Spring Boot
  url: https://spring.io/projects/spring-boot

springFrameworkOverview:
  type: Web
  title: Spring Framework Overview
  url: https://docs.spring.io/spring-framework/reference/overview.html

springFrameworkHistory:
  type: Web
  title: History of Spring and the Spring Framework
  url: https://docs.spring.io/spring-framework/reference/overview.html#overview-history

springAndSpringBootComparison:
  type: Web
  title: A Comparison Between Spring and Spring Boot
  publisher: Baeldung
  author: baeldung
  date: 2024-05-11
  url: https://www.baeldung.com/spring-vs-spring-boot

whatIsREST:
  type: Web
  title: What is REST?
  publisher: Codecademy Team
  url: https://www.codecademy.com/article/what-is-rest

httpSpecsGET:
  type: Web
  title: Method Definitions - GET
  url: https://httpwg.org/specs/rfc9110.html#GET

httpSpecsPOST:
  type: Web
  title: Method Definitions - POST
  url: https://httpwg.org/specs/rfc9110.html#POST

httpSpecsPUT:
  type: Web
  title: Method Definitions - PUT
  url: https://httpwg.org/specs/rfc9110.html#PUT

httpSpecsDELETE:
  type: Web
  title: Method Definitions - DELETE
  url: https://httpwg.org/specs/rfc9110.html#DELETE

idempotentMethods:
  type: Web
  title: Idempotent Methods
  url: https://httpwg.org/specs/rfc9110.html#idempotent.methods

httpStatusCodes:
  type: Web
  title: Status Codes
  url: https://httpwg.org/specs/rfc9110.html#status.codes

modelViewControllerMdn:
  type: Web
  title: MVC
  url: https://developer.mozilla.org/en-US/docs/Glossary/MVC

ormWikipedia:
  type: Web
  title: Object–relational mapping
  publisher: Wikipedia
  url: https://en.wikipedia.org/wiki/Object%E2%80%93relational_mapping

ormItSchulung:
  type: Web
  title: Was ist Object-Relational Mapping (ORM)
  publisher: IT-Schulungen.com
  url: https://www.it-schulungen.com/wir-ueber-uns/wissensblog/was-ist-object-relational-mapping-orm.html

codecademyCRUD:
  type: Web
  title: What is CRUD? Explained
  url: https://www.codecademy.com/article/what-is-crud-explained

springMappingRequests:
  type: Web
  title: Mapping Requests
  url: https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller/ann-requestmapping.html

springControllersUriPatterns:
  type: Web
  title: URI Patterns
  url: https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller/ann-requestmapping.html#mvc-ann-requestmapping-uri-templates

springRestErrorHandling:
  type: Web
  title: Error Handling for REST with Spring in Kotlin
  url: https://www.baeldung.com/kotlin/spring-rest-error-handling

springControllerAdvice:
  type: Web
  title: Controller Advice
  url: https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller/ann-advice.html

transactions101:
  type: Web
  title: "Transactions 101: when and how to use them in the Spring Framework"
  url: https://www.twoday.lt/blog/transactions-101-when-and-how-to-use-them-in-the-spring-framework

whenToUseTransactionalStackOverflow:
  type: Web
  title: When should we use @Transactional annotation?
  url: https://stackoverflow.com/questions/78132448/when-should-we-use-transactional-annotation
