direction: right

Containerization.Docker: {
    icon: icons/logos--docker-icon.svg
}
Containerization.Podman: {
    icon: icons/devicon--podman.svg
}

Database: {
    icon: icons/devicon--postgresql.svg
}

Backend: {
    icon: icons/devicon--spring.svg
}

Frontend: {
    icon: icons/devicon--svelte.svg
}

Database <-> Backend
Backend <-> Frontend

Containerization -- Database
Containerization -- Backend
Containerization -- Frontend
